import {
  heroUsers,
  heroChevronDown,
  heroDocumentChartBar,
  heroDocument,
  heroChartPie,
  heroBell,
  heroBars3,
  heroSquare3Stack3d,
  heroHandRaised,
  heroTag,
  heroBuildingStorefront,
  heroShoppingBag,
  heroTruck,
  heroHome,
  heroBookOpen,
  heroAcademicCap,
  heroArrowTrendingUp,
  heroClipboardDocumentCheck,
} from '@ng-icons/heroicons/outline';

export const getImportsIcons = {
  heroUsers,
  heroChevronDown,
  heroDocumentChartBar,
  heroDocument,
  heroChartPie,
  heroBell,
  heroBars3,
  heroSquare3Stack3d,
  heroHandRaised,
  heroTag,
  heroBuildingStorefront,
  heroShoppingBag,
  heroTruck,
  heroHome,
  heroBookOpen,
  heroAcademicCap,
  heroArrowTrendingUp,
  heroClipboardDocumentCheck,
};
